---
local_route: 192.168.50.1
external_port: 9022
internal_service_hostname: 192.168.50.1

pid_filename: /tmp/cloud_controller.pid
newrelic_enabled: false
development_mode: false

message_bus_servers:
  - nats://nats:nats@10.244.0.6:4222

external_protocol: https
external_domain: api.bosh-lite.com

system_domain_organization: 
system_domain: bosh-lite.com
app_domains: [ bosh-lite.com ]

jobs:
  global:
    timeout_in_seconds: 14400

app_events:
  cutoff_age_in_days: 31

app_usage_events:
  cutoff_age_in_days: 31

service_usage_events:
  cutoff_age_in_days: 31

audit_events:
  cutoff_age_in_days: 31

failed_jobs:
  cutoff_age_in_days: 31

completed_tasks:
  cutoff_age_in_days: 31

default_app_memory: 256
default_app_disk_in_mb: 1024
maximum_app_disk_in_mb: 2048

instance_file_descriptor_limit: 16384

request_timeout_in_seconds: 900

cc_partition: default

bulk_api:
  auth_user: bulk_api
  auth_password: "bulk-password"

internal_api:
  auth_user: internal_user
  auth_password: "internal-password"

nginx:
  use_nginx: false
  instance_socket: "/var/vcap/sys/run/cloud_controller_ng/cloud_controller.sock"

index: 0
name: api_z1
route_services_enabled: true
volume_services_enabled: true

info:
  name: ""
  build: ""
  version: 0
  support_address: "http://support.cloudfoundry.com"
  description: ""
  app_ssh_endpoint: ssh.bosh-lite.com:2222
  app_ssh_host_key_fingerprint: a6:d1:08:0b:b0:cb:9b:5f:c4:ba:44:2a:97:26:19:8a
  app_ssh_oauth_client: ssh-proxy

logging:
  file: /tmp/cloud_controller.log
  level: debug2

loggregator:
  router: 127.0.0.1:3457
  url: wss://loggregator.bosh-lite.com:443

doppler:
  enabled: false

db: &db
  database: postgres://ccadmin:admin@10.244.0.30:5524/ccdb
  max_connections: 25
  pool_timeout: 10
  log_level: debug2

login:
  url: https://login.bosh-lite.com

uaa:
  url: https://uaa.bosh-lite.com
  resource_id: cloud_controller,cloud_controller_service_permissions
  verification_key: |
      -----BEGIN PUBLIC KEY-----
      MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHFr+KICms+tuT1OXJwhCUmR2d
      KVy7psa8xzElSyzqx7oJyfJ1JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMX
      qHxf+ZH9BL1gk9Y6kCnbM5R60gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBug
      spULZVNRxq7veq/fzwIDAQAB
      -----END PUBLIC KEY-----

hm9000:
  url: https://hm9000.bosh-lite.com
  internal_url: "http://10.244.0.142:5155"

# App staging parameters
staging:
  timeout_in_seconds: 900
  minimum_staging_memory_mb: 1024
  minimum_staging_disk_mb: 6144
  minimum_staging_file_descriptor_limit: 16384
  auth:
    user: upload-user
    password: "upload-password"

default_health_check_timeout: 60
maximum_health_check_timeout: 180

quota_definitions:
  default:
    memory_limit: 10240
    non_basic_services_allowed: true
    total_routes: 1000
    total_service_keys: 1000
    total_services: 100

default_quota_definition: default

resource_pool:
  blobstore_type: webdav
  webdav_config:
    blobstore_timeout: 5
    public_endpoint: http://blobstore.bosh-lite.com
    private_endpoint: https://blobstore.service.cf.internal:4443
    username: blobstore-username
    password: blobstore-password
  minimum_size: 65536
  maximum_size: 536870912
  resource_directory_key: bosh-lite.com-cc-resources
  cdn:
    uri: 
    key_pair_id: 
    private_key: ""
  fog_connection: {}

packages:
  blobstore_type: webdav
  webdav_config:
    blobstore_timeout: 5
    public_endpoint: http://blobstore.bosh-lite.com
    private_endpoint: https://blobstore.service.cf.internal:4443
    username: blobstore-username
    password: blobstore-password
  app_package_directory_key: bosh-lite.com-cc-packages
  max_valid_packages_stored: 5
  max_package_size: 1073741824
  cdn:
    uri: 
    key_pair_id: 
    private_key: ""
  fog_connection: {}

droplets:
  blobstore_type: webdav
  webdav_config:
    blobstore_timeout: 5
    public_endpoint: http://blobstore.bosh-lite.com
    private_endpoint: https://blobstore.service.cf.internal:4443
    username: blobstore-username
    password: blobstore-password
  droplet_directory_key: bosh-lite.com-cc-droplets
  cdn:
    uri: 
    key_pair_id: 
    private_key: ""
  fog_connection: {}
  max_staged_droplets_stored: 5

buildpacks:
  blobstore_type: webdav
  webdav_config:
    blobstore_timeout: 5
    public_endpoint: http://blobstore.bosh-lite.com
    private_endpoint: https://blobstore.service.cf.internal:4443
    username: blobstore-username
    password: blobstore-password
  buildpack_directory_key: bosh-lite.com-cc-buildpacks
  cdn:
    uri: 
    key_pair_id: 
    private_key: ""
  fog_connection: {}

db_encryption_key: db-encryption-key

flapping_crash_count_threshold: 3

disable_custom_buildpacks: false

broker_client_timeout_seconds: 70
broker_client_default_async_poll_interval_seconds: 60
broker_client_max_async_poll_duration_minutes: 10080

renderer:
  max_results_per_page: 100
  default_results_per_page: 50
  max_inline_relations_depth: 2

uaa_client_name: "cc-service-dashboards"
uaa_client_secret: cc-broker-secret
uaa_client_scope: openid,cloud_controller_service_permissions.read

cloud_controller_username_lookup_client_name: "cloud_controller_username_lookup"
cloud_controller_username_lookup_client_secret: cloud-controller-username-lookup-secret

users_can_select_backend: true
allow_app_ssh_access: true
default_to_diego_backend: false
diego_nsync_url: http://10.244.16.14:8787
diego_stager_url: http://10.244.16.14:8888
diego_tps_url: http://10.244.16.14:1518

skip_cert_verify: true

install_buildpacks: 
- name: staticfile_buildpack
  package: staticfile-buildpack
- name: java_buildpack
  package: buildpack_java
- name: ruby_buildpack
  package: ruby-buildpack
- name: nodejs_buildpack
  package: nodejs-buildpack
- name: go_buildpack
  package: go-buildpack
- name: python_buildpack
  package: python-buildpack
- name: php_buildpack
  package: php-buildpack
- name: binary_buildpack
  package: binary-buildpack

app_bits_upload_grace_period_in_seconds: 1200

security_group_definitions: [{"name":"public_networks","rules":[{"destination":"0.0.0.0-9.255.255.255","protocol":"all"},{"destination":"11.0.0.0-169.253.255.255","protocol":"all"},{"destination":"169.255.0.0-172.15.255.255","protocol":"all"},{"destination":"172.32.0.0-192.167.255.255","protocol":"all"},{"destination":"192.169.0.0-255.255.255.255","protocol":"all"}]},{"name":"dns","rules":[{"destination":"0.0.0.0/0","ports":"53","protocol":"tcp"},{"destination":"0.0.0.0/0","ports":"53","protocol":"udp"}]},{"name":"services","rules":[{"destination":"10.244.1.0/24","protocol":"all"},{"destination":"10.244.3.0/24","protocol":"all"}]},{"name":"load_balancer","rules":[{"destination":"10.244.0.34","protocol":"all"}]},{"name":"user_bosh_deployments","rules":[{"destination":"10.244.4.0-10.254.0.0","protocol":"all"}]}]
default_running_security_groups: ["public_networks","dns","services","load_balancer","user_bosh_deployments"]
default_staging_security_groups: ["public_networks","dns"]

allowed_cors_domains: []

dea_advertisement_timeout_in_seconds: 15
placement_top_stager_percentage: 10

system_hostnames: ["api", "uaa", "login", "doppler", "loggregator", "hm9000"]
