---
local_route: 127.0.0.1
external_port: 8181
pid_filename: /tmp/cloud_controller.pid
message_bus_servers:
  - nats://127.0.0.1:4222

external_protocol: http
external_domain: api2.vcap.me
internal_service_hostname: api.internal.cf

system_domain_organization: the-system_domain-org-name
system_domain: vcap.me
app_domains:
  - customer-app-domain1.com
  - customer-app-domain2.com
system_hostnames:
  - api
  - uaa
  - login
  - doppler
  - loggregator
  - hm9000

jobs:
  global:
    timeout_in_seconds: 14400

app_events:
  cutoff_age_in_days: 31

app_usage_events:
  cutoff_age_in_days: 31

service_usage_events:
  cutoff_age_in_days: 31

audit_events:
  cutoff_age_in_days: 31

failed_jobs:
  cutoff_age_in_days: 31

completed_tasks:
  cutoff_age_in_days: 31

default_app_memory: 1024 #mb
default_app_disk_in_mb: 1024
maximum_app_disk_in_mb: 2048

broker_client_default_async_poll_interval_seconds: 60
broker_client_max_async_poll_duration_minutes: 10080

info:
  name: "vcap"
  build: "2222"
  version: 2
  support_address: "http://support.cloudfoundry.com"
  description: "Cloud Foundry sponsored by Pivotal"
  app_ssh_endpoint: "ssh.system.domain.example.com:2222"
  app_ssh_host_key_fingerprint: "47:0d:d1:c8:c3:3d:0a:36:d1:49:2f:f2:90:27:31:d0"
  app_ssh_oauth_client_id: "ssh-proxy"

nginx:
  use_nginx: false
  instance_socket: "/var/vcap/sys/run/cloud_controller_ng/cloud_controller.sock"

logging:
  file: /tmp/cloud_controller.log
  level: debug2

loggregator:
  router: "127.0.0.1:3456"
  url: "ws://loggregator.vcap.me:80"

doppler:
  enabled: false

db:
  max_connections: 32
  pool_timeout: 10

uaa:
  url: "http://localhost:8080/uaa"
  resource_id: "cloud_controller"
  symmetric_secret: "tokensecret"
  ca_file: "/var/vcap/job/cloud_controller_ng/config/certs/uaa_ca.crt"

hm9000:
  url: "http://localhost:5155"
  internal_url: "https://localhost:5155/internal"

routing_api:
  url: "http://localhost:3000"
  routing_client_name: 'routing-client'
  routing_client_secret: 'routing-secret'

route_services_enabled: true
volume_services_enabled: true

cc_partition: ng

bulk_api:
  auth_user: bulk_user
  auth_password: bulk_password

internal_api:
  auth_user: internal_user
  auth_password: internal_password

# App staging parameters
staging:
  # Max duration for staging process
  timeout_in_seconds: 120 # secs
  minimum_staging_memory_mb: 1024
  minimum_staging_disk_mb: 4096
  auth:
    user: zxsfhgjg
    password: ZNVfdase9

quota_definitions:
  default:
    memory_limit: 10240
    total_services: 100
    non_basic_services_allowed: true
    total_routes: 1000

default_quota_definition: default

resource_pool:
  resource_directory_key: "spec-cc-resources"
  fog_connection:
    blobstore_timeout: 5
    provider: "AWS"
    aws_access_key_id: "fake_aws_key_id"
    aws_secret_access_key: "fake_secret_access_key"

packages:
  app_package_directory_key: "cc-packages"
  fog_connection:
    blobstore_timeout: 5
    provider: "AWS"
    aws_access_key_id: "fake_aws_key_id"
    aws_secret_access_key: "fake_secret_access_key"

droplets:
  droplet_directory_key: cc-droplets
  fog_connection:
    blobstore_timeout: 5
    provider: "AWS"
    aws_access_key_id: "fake_aws_key_id"
    aws_secret_access_key: "fake_secret_access_key"

buildpacks:
  buildpack_directory_key: cc-buildpacks
  fog_connection:
    blobstore_timeout: 5
    provider: "AWS"
    aws_access_key_id: "fake_aws_key_id"
    aws_secret_access_key: "fake_secret_access_key"

db_encryption_key: "asdfasdfasdf"

varz_port: 7800
varz_user: varz
varz_password: password

default_health_check_timeout: 60
maximum_health_check_timeout: 180

flapping_crash_count_threshold: 3

disable_custom_buildpacks: false
broker_client_timeout_seconds: 60

uaa_client_name: 'cc-service-dashboards'
uaa_client_secret: 'some-sekret'
uaa_client_scope: openid,cloud_controller_service_permissions.read

cloud_controller_username_lookup_client_name: 'username_lookup_client_name'
cloud_controller_username_lookup_client_secret: 'username_lookup_secret'

users_can_select_backend: true
allow_app_ssh_access: true
diego_nsync_url: http://nsync.service.cf.internal:8787
diego_stager_url: http://stager.service.cf.internal:8888
diego_tps_url: http://tps.service.cf.internal:1518

renderer:
  max_results_per_page: 100
  default_results_per_page: 50
  max_inline_relations_depth: 3

install_buildpacks:
  - name: java_buildpack
    package: buildpack_java
  - name: ruby_buildpack
    package: buildpack_ruby
  - name: node_buildpack
    package: buildpack_node

security_group_definitions:
- name: dummy1
  rules: []
- name: dummy2
  rules: []

default_staging_security_groups:
- dummy3
default_running_security_groups:
- dummy4

allowed_cors_domains:
- http://*.appspot.com
- http://*.inblue.net
- http://talkoncorners.com
- http://borrowedheaven.org
