---
local_route: 127.0.0.1
port: 8181
pid_filename: /tmp/cloud_controller.pid
nats_uri: nats://127.0.0.1:4222

external_domain: api2.vcap.me
system_domains:
  - vcap.me

bootstrap_admin_email: sre@vmware.com

info:
  name: "vcap"
  build: "2222"
  version: 2
  support_address: "http://support.cloudfoundry.com"
  description: "VMware's Cloud Application Platform"
  api_version: "2.0.0"
# TODO: put back once json schema is sorted out
# allow_debug: false

nginx:
  use_nginx: false
  instance_socket: "/var/vcap/sys/run/cloud_controller_ng/cloud_controller.sock"

logging:
  level: debug2

db:
  database: "sqlite:///tmp/cloud_controller.db"
  max_connections: 32
  pool_timeout: 10

redis:
  host: 127.0.0.1
  port: 5454
  password: secret

uaa:
  url: "http://localhost:8080/uaa"
  resource_id: "cloud_controller"
  symmetric_secret: "tokensecret"

cc_partition: ng

bulk_api:
  auth_user: bulk_user
  auth_password: bulk_password

service_lifecycle:
  max_upload_size: 1
  upload_token: changeme
  upload_timeout: 2
  serialization_data_server: []

# App staging parameters
staging:
  # Max duration for staging process
  max_staging_runtime: 120 # secs
  auth:
    user: zxsfhgjg
    password: ZNVfdase9

quota_definitions:
  free:
    non_basic_services_allowed: false
    total_services: 2
    free_memory_limit: 1024 # 1 GB
    paid_memory_limit: 0
  paid:
    non_basic_services_allowed: true
    total_services: 32
    free_memory_limit: 1024 # 1 GB
    paid_memory_limit: 32768 # 32 GB
  runaway:
    non_basic_services_allowed: true
    total_services: 500
    free_memory_limit: 1024 # 1 GB
    paid_memory_limit: 204800 # 200 GB

default_quota_definition: free

resource_pool:
  resource_directory_key: cc-resources
  fog_connection:
    provider: Local
    local_root: /tmp

packages:
  resource_directory_key: cc-packages
  fog_connection:
    provider: Local
    local_root: /tmp
