---
port: 8181
pid_filename: /tmp/cloud_controller.pid
nats_uri: nats://127.0.0.1:4222

external_domain: api2.vcap.me
serving_domain: vcap.me

bootstrap_admin_email: sre@vmware.com

info:
  name: "vcap"
  build: "2222"
  version: 2
  support_address: "http://support.cloudfoundry.com"
  description: "VMware's Cloud Application Platform"
  api_version: "2.0.0"
# TODO: put back once json schema is sorted out
# allow_debug: false

nginx:
  instance_socket: "/var/vcap/sys/run/cloud_controller_ng/cloud_controller.sock"

logging:
  level: debug2

db:
  database: "sqlite:///tmp/cloud_controller.db"
  max_connections: 32
  pool_timeout: 10

redis:
  host: 127.0.0.1
  port: 5454
  password: secret

uaa:
  url: "http://localhost:8080/uaa"
  resource_id: "cloud_controller"
  symmetric_secret: "tokensecret"

quota_manager:
  policy: "MoneyMakerApproval" # can also be BlindApproval
  base_url: "http://localhost:31004/v1/quota"
  auth_token: "testtoken"
  http_timeout_sec: 2

cc_partition: ng

bulk_api:
  auth_user: bulk_user
  auth_password: bulk_password

# App staging parameters
staging:
  # Max duration for staging process
  max_staging_runtime: 120 # secs
  auth:
    user: zxsfhgjg
    password: ZNVfdase9

# TODO: this will be removed when we do full runtime/framework
# db population when we work on real running app support
#
# The first entry in the runtimes array is the default runtime for that
# framework.
legacy_framework_manifest:
  django:
    name: django
    runtimes:
    - name: python2
      version: 2.6.5
      description: Python 2.6.5
    appservers: []

    detection:
    - "*.py": .
  grails:
    name: grails
    runtimes:
    - name: java
      version: "1.6"
      description: Java 6
    appservers:
    - name: tomcat
      description: Tomcat
    detection:
    - "*.war": true
  java_web:
    name: java_web
    runtimes:
    - name: java
      version: "1.6"
      description: Java 6
    appservers:
    - name: tomcat
      description: Tomcat
    detection:
    - "*.war": true
  lift:
    name: lift
    runtimes:
    - name: java
      version: "1.6"
      description: Java 6
    appservers:
    - name: tomcat
      description: Tomcat
    detection:
    - "*.war": true
  node:
    name: node
    runtimes:
    - name: node08
      version: 0.8.2
      description: Node.js
    - name: node06
      version: 0.6.8
      description: Node.js
    - name: node
      version: 0.4.12
      description: Node.js
    appservers: []

    detection:
    - "*.js": .
  otp_rebar:
    name: otp_rebar
    runtimes:
    - name: erlangR14B02
      version: R14B02
      description: Erlang R14B02
    appservers: []

    detection:
    - releases/*/*.rel: .
  php:
    name: php
    runtimes:
    - name: php
      version: "5.3"
      description: PHP 5
    appservers:
    - name: apache
      description: Apache
    detection:
    - "*.php": true
  rack:
    name: rack
    runtimes:
    - name: ruby18
      version: 1.8.7
      description: Ruby 1.8.7
    - name: ruby19
      version: 1.9.2p180
      description: Ruby 1.9.2
    appservers:
    - name: thin
      description: Thin
    detection:
    - config.ru: true
    - config/environment.rb: false
  rails3:
    name: rails3
    runtimes:
    - name: ruby18
      version: 1.8.7
      description: Ruby 1.8.7
    - name: ruby19
      version: 1.9.2p180
      description: Ruby 1.9.2
    appservers:
    - name: thin
      description: Thin
    detection:
    - config/application.rb: true
    - config/environment.rb: true
  sinatra:
    name: sinatra
    runtimes:
    - name: ruby18
      version: 1.8.7
      description: Ruby 1.8.7
    - name: ruby19
      version: 1.9.2p180
      description: Ruby 1.9.2
    appservers:
    - name: thin
      description: Thin
    detection:
    - "*.rb": require 'sinatra'|require "sinatra"
    - config.ru: false
    - config/environment.rb: false
  spring:
    name: spring
    runtimes:
    - name: java
      version: "1.6"
      description: Java 6
    appservers:
    - name: tomcat
      description: Tomcat
    detection:
    - "*.war": true
  standalone:
    name: standalone
    runtimes:
    - name: ruby18
      version: 1.8.7
      description: Ruby 1.8.7
    - name: ruby19
      version: 1.9.2p180
      description: Ruby 1.9.2
    - name: python2
      version: 2.6.5
      description: Python 2.6.5
    - name: java
      version: "1.6"
      description: Java 6
    - name: node
      version: 0.4.12
      description: Node.js
    - name: node06
      version: 0.6.8
      description: Node.js
    - name: erlangR14B02
      version: R14B02
      description: Erlang R14B02
    - name: php
      version: "5.3"
      description: PHP 5
    appservers: []

    detection:
  wsgi:
    name: wsgi
    runtimes:
    - name: python2
      version: 2.6.5
      description: Python 2.6.5
    appservers: []

    detection:
    - "*.py": .
