---
local_route: 127.0.0.1
external_port: 8181
pid_filename: /tmp/cloud_controller.pid
message_bus_servers:
  - nats://127.0.0.1:4222

external_domain: api2.vcap.me

bootstrap_admin_email: sre@vmware.com

system_domain_organization: the-system_domain-org-name
system_domain: vcap.me
app_domains:
  - customer-app-domain1.com
  - customer-app-domain2.com

jobs:
  global:
    timeout_in_seconds: 14400

app_events:
  cutoff_age_in_days: 31

app_usage_events:
  cutoff_age_in_days: 31

audit_events:
  cutoff_age_in_days: 31

default_app_memory: 1024 #mb
maximum_app_disk_in_mb: 2048

info:
  name: "vcap"
  build: "2222"
  version: 2
  support_address: "http://support.cloudfoundry.com"
  description: "Cloud Foundry sponsored by Pivotal"
  api_version: "2.0.0"

nginx:
  use_nginx: false
  instance_socket: "/var/vcap/sys/run/cloud_controller_ng/cloud_controller.sock"

logging:
  file: /tmp/cloud_controller.log
  level: debug2

loggregator:
  router: "127.0.0.1:3456"
  shared_secret: "loggregatorsecret"
  url: "ws://loggregator.vcap.me:80"

db:
  database: "sqlite:///tmp/cloud_controller.db"
  max_connections: 32
  pool_timeout: 10

uaa:
  url: "http://localhost:8080/uaa"
  resource_id: "cloud_controller"
  symmetric_secret: "tokensecret"

cc_partition: ng

bulk_api:
  auth_user: bulk_user
  auth_password: bulk_password

# App staging parameters
staging:
  # Max duration for staging process
  max_staging_runtime: 120 # secs
  minimum_staging_memory_mb: 1024
  auth:
    user: zxsfhgjg
    password: ZNVfdase9

quota_definitions:
  default:
    memory_limit: 10240
    total_services: 100
    non_basic_services_allowed: true
    total_routes: 1000
    trial_db_allowed: true

default_quota_definition: default

resource_pool:
  resource_directory_key: "spec-cc-resources"
  fog_connection:
    provider: "AWS"
    aws_access_key_id: "fake_aws_key_id"
    aws_secret_access_key: "fake_secret_access_key"

packages:
  app_package_directory_key: "cc-packages"
  fog_connection:
    provider: "AWS"
    aws_access_key_id: "fake_aws_key_id"
    aws_secret_access_key: "fake_secret_access_key"

droplets:
  droplet_directory_key: cc-droplets
  fog_connection:
    provider: "AWS"
    aws_access_key_id: "fake_aws_key_id"
    aws_secret_access_key: "fake_secret_access_key"

buildpacks:
  buildpack_directory_key: cc-buildpacks
  fog_connection:
    provider: "AWS"
    aws_access_key_id: "fake_aws_key_id"
    aws_secret_access_key: "fake_secret_access_key"

db_encryption_key: "asdfasdfasdf"

trial_db:
  guid: "78ad16cf-3c22-4427-a982-b9d35d746914"

tasks_disabled: false

hm9000_noop: true

varz_port: 7800
varz_user: varz
varz_password: password

maximum_health_check_timeout: 180

flapping_crash_count_threshold: 3

disable_custom_buildpacks: false
broker_client_timeout_seconds: 60

diego: false

renderer:
  max_results_per_page: 100
  default_results_per_page: 50
  max_inline_relations_depth: 3
