---
port: 8181
pid_filename: /var/vcap/sys/run/cloud_controller.pid
nats_uri: nats://127.0.0.1:4222

logging:
  level: debug2

db:
  database: "sqlite:///tmp/cloud_controller.db"
  max_connections: 32
  pool_timeout: 10

uaa:
  resource_id: "cloud_controller"
  symmetric_secret: "symmetric secret"

quota_manager:
  policy: "MoneyMakerApproval" # can also be BlindApproval
  base_url: "http://localhost:31004/v1/quota"
  auth_token: "testtoken"
  http_timeout_sec: 2

secrets:
  user_token:
    key: "token key goes here"
    duration: 604800            # 7 * 24 * 60 * 60 (= 1week)
