name: Unit Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    container:
      image: "cloudfoundry/capi:ruby-units"
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: bundle install
    - name: Run Rubocop
      run: bundle exec rake rubocop
    - uses: ravsamhq/notify-slack-action@v1.1
      if: always()
      with:
        status: ${{ job.status }}
        notify_when: 'failure' # default is 'success,failure,warnings'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
  test_postgres:
    runs-on: ubuntu-latest
    container:
      image: "cloudfoundry/capi:ruby-units"
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: bundle install
    - name: Setup PostgreSQL
      run: service postgresql restart
    - name: Run tests
      run: DB=postgres bundle exec rake spec:all
    - uses: ravsamhq/notify-slack-action@v1.1
      if: always()
      with:
        status: ${{ job.status }}
        notify_when: 'failure' # default is 'success,failure,warnings'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
  test_mysql:
    runs-on: ubuntu-latest
    container:
      image: "cloudfoundry/capi:ruby-units"
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: bundle install
    - name: Setup MySQL
      run: |
        find /var/lib/mysql/mysql -exec touch -c -a {} +
        service mysql restart
    - name: Run tests
      run: DB=mysql bundle exec rake spec:all
    - uses: ravsamhq/notify-slack-action@v1.1
      if: always()
      with:
        status: ${{ job.status }}
        notify_when: 'failure' # default is 'success,failure,warnings'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
  test_mysql8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Setup MySQL
      run: |
        sudo systemctl start mysql.service
    - name: Run tests
      run: DB=mysql MYSQL_CONNECTION_PREFIX=mysql2://root:root@localhost:3306 bundle exec rake spec:all
    - uses: ravsamhq/notify-slack-action@v1.1
      if: always()
      with:
        status: ${{ job.status }}
        notify_when: 'failure' # default is 'success,failure,warnings'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
  test_docs:
    runs-on: ubuntu-latest
    container:
      image: "cloudfoundry/capi:rc-docs"
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          bundle install
          cd docs/v3
          bundle install
          cd -
      - name: Run docs tests
        run: bundle exec rake check_doc_links
      - uses: ravsamhq/notify-slack-action@v1.1
        if: always()
        with:
          status: ${{ job.status }}
          notify_when: 'failure' # default is 'success,failure,warnings'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
